# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 04:23
from __future__ import unicode_literals

import blog.models
import datetime
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=5000)),
                ('blog_photo', models.ImageField(upload_to=blog.models._image_path)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('tags', models.CharField(blank=True, max_length=30)),
            ],
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
