# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171218_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
