# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161012_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
