# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:23
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
