# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 00:29
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171219_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
