---
- name: Register the old default file
  stat: path=/etc/nginx/sites-available/default.old
  register: default_stat

- name: Rename old default file
  command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.old
  when: not default_stat.stat.exists

- name: Create a new default file for nginx
  template:
    src=../templates/simple_nginx_config 
    dest=/etc/nginx/sites-available/default

- name: Restart the nginx service
  service:
    name=nginx
    state=restarted

- name: Copy over system.d config
  include_vars:
    file: ../vars/aws_vars.yml
  template:
    src=../templates/systemd_config
    dest=/etc/systemd/system/kh_site.service

- name: Start up the site's service
  systemd:
    name=kh_site
    state=restarted
